# Generated by Django 3.0.3 on 2021-01-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desease',
            name='desease_display_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
