# Generated by Django 3.0.3 on 2021-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_desease_desease_display_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desease',
            old_name='desease_description',
            new_name='Disease_description',
        ),
        migrations.RenameField(
            model_name='desease',
            old_name='desease_display_image',
            new_name='Disease_display_image',
        ),
        migrations.RenameField(
            model_name='desease',
            old_name='desease_name',
            new_name='Disease_name',
        ),
        migrations.RenameField(
            model_name='desease',
            old_name='desease_remidies',
            new_name='Disease_remidies',
        ),
        migrations.AddField(
            model_name='desease',
            name='Disease_symptoms',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
