# Generated by Django 3.0.3 on 2021-01-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210126_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desease',
            name='Disease_display_image',
        ),
    ]
